/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  HealthApiHealthGet200
} from '../index.schemas';


export const getHealthApiHealthGetResponseMock = (): HealthApiHealthGet200 => ({
        [faker.string.alphanumeric(5)]: faker.string.alpha({length: {min: 10, max: 20}})
      })


export const getHealthApiHealthGetMockHandler = (overrideResponse?: HealthApiHealthGet200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthApiHealthGet200> | HealthApiHealthGet200), options?: RequestHandlerOptions) => {
  return http.get('*/api/health', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthApiHealthGetResponseMock(),
      { status: 200
      })
  }, options)
}
export const getHealthMock = () => [
  getHealthApiHealthGetMockHandler()]
