/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HealthApiHealthGet200
} from '../index.schemas';




  export const getHealth = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Health
 */
const healthApiHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthApiHealthGet200>> => {
    return axiosInstance.get(
      `/api/health`,options
    );
  }
return {healthApiHealthGet}};
export type HealthApiHealthGetResult = AxiosResponse<HealthApiHealthGet200>
