/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Get Me
 */
export const GetMeApiUsersMeGetResponse = zod.object({
  "id": zod.string().uuid(),
  "email": zod.string(),
  "created_at": zod.string().datetime({})
})

