/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  TrackedProductListResponse,
  TrackedProductResponse
} from '../index.schemas';


export const getListTrackedProductsApiTrackedProductsGetResponseMock = (overrideResponse: Partial<Extract<TrackedProductListResponse, object>> = {}): TrackedProductListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), user_id: faker.string.uuid(), source_url: faker.string.alpha({length: {min: 10, max: 20}}), source_platform: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_title: faker.string.alpha({length: {min: 10, max: 20}}), source_image_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_price_amount: faker.helpers.arrayElement([faker.helpers.fromRegExp('^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$'),null,]), source_currency: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), normalized_query: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), product_fingerprint: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), monitoring_status: faker.string.alpha({length: {min: 10, max: 20}}), restock_alert_enabled: faker.datatype.boolean(), lowest_price_tracking_enabled: faker.datatype.boolean(), last_checked_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), ...overrideResponse})

export const getCreateTrackedProductApiTrackedProductsPostResponseMock = (overrideResponse: Partial<Extract<TrackedProductResponse, object>> = {}): TrackedProductResponse => ({id: faker.string.uuid(), user_id: faker.string.uuid(), source_url: faker.string.alpha({length: {min: 10, max: 20}}), source_platform: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_title: faker.string.alpha({length: {min: 10, max: 20}}), source_image_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_price_amount: faker.helpers.arrayElement([faker.helpers.fromRegExp('^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$'),null,]), source_currency: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), normalized_query: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), product_fingerprint: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), monitoring_status: faker.string.alpha({length: {min: 10, max: 20}}), restock_alert_enabled: faker.datatype.boolean(), lowest_price_tracking_enabled: faker.datatype.boolean(), last_checked_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetTrackedProductApiTrackedProductsTrackedProductIdGetResponseMock = (overrideResponse: Partial<Extract<TrackedProductResponse, object>> = {}): TrackedProductResponse => ({id: faker.string.uuid(), user_id: faker.string.uuid(), source_url: faker.string.alpha({length: {min: 10, max: 20}}), source_platform: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_title: faker.string.alpha({length: {min: 10, max: 20}}), source_image_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_price_amount: faker.helpers.arrayElement([faker.helpers.fromRegExp('^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$'),null,]), source_currency: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), normalized_query: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), product_fingerprint: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), monitoring_status: faker.string.alpha({length: {min: 10, max: 20}}), restock_alert_enabled: faker.datatype.boolean(), lowest_price_tracking_enabled: faker.datatype.boolean(), last_checked_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateTrackedProductApiTrackedProductsTrackedProductIdPatchResponseMock = (overrideResponse: Partial<Extract<TrackedProductResponse, object>> = {}): TrackedProductResponse => ({id: faker.string.uuid(), user_id: faker.string.uuid(), source_url: faker.string.alpha({length: {min: 10, max: 20}}), source_platform: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_title: faker.string.alpha({length: {min: 10, max: 20}}), source_image_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_price_amount: faker.helpers.arrayElement([faker.helpers.fromRegExp('^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$'),null,]), source_currency: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), normalized_query: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), product_fingerprint: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), monitoring_status: faker.string.alpha({length: {min: 10, max: 20}}), restock_alert_enabled: faker.datatype.boolean(), lowest_price_tracking_enabled: faker.datatype.boolean(), last_checked_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostResponseMock = (overrideResponse: Partial<Extract<TrackedProductResponse, object>> = {}): TrackedProductResponse => ({id: faker.string.uuid(), user_id: faker.string.uuid(), source_url: faker.string.alpha({length: {min: 10, max: 20}}), source_platform: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_title: faker.string.alpha({length: {min: 10, max: 20}}), source_image_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_price_amount: faker.helpers.arrayElement([faker.helpers.fromRegExp('^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$'),null,]), source_currency: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), normalized_query: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), product_fingerprint: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), monitoring_status: faker.string.alpha({length: {min: 10, max: 20}}), restock_alert_enabled: faker.datatype.boolean(), lowest_price_tracking_enabled: faker.datatype.boolean(), last_checked_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getRestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostResponseMock = (overrideResponse: Partial<Extract<TrackedProductResponse, object>> = {}): TrackedProductResponse => ({id: faker.string.uuid(), user_id: faker.string.uuid(), source_url: faker.string.alpha({length: {min: 10, max: 20}}), source_platform: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_title: faker.string.alpha({length: {min: 10, max: 20}}), source_image_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_price_amount: faker.helpers.arrayElement([faker.helpers.fromRegExp('^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$'),null,]), source_currency: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), normalized_query: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), product_fingerprint: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), monitoring_status: faker.string.alpha({length: {min: 10, max: 20}}), restock_alert_enabled: faker.datatype.boolean(), lowest_price_tracking_enabled: faker.datatype.boolean(), last_checked_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getRefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostResponseMock = (overrideResponse: Partial<Extract<TrackedProductResponse, object>> = {}): TrackedProductResponse => ({id: faker.string.uuid(), user_id: faker.string.uuid(), source_url: faker.string.alpha({length: {min: 10, max: 20}}), source_platform: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_title: faker.string.alpha({length: {min: 10, max: 20}}), source_image_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), source_price_amount: faker.helpers.arrayElement([faker.helpers.fromRegExp('^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$'),null,]), source_currency: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), normalized_query: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), product_fingerprint: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), monitoring_status: faker.string.alpha({length: {min: 10, max: 20}}), restock_alert_enabled: faker.datatype.boolean(), lowest_price_tracking_enabled: faker.datatype.boolean(), last_checked_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getListTrackedProductsApiTrackedProductsGetMockHandler = (overrideResponse?: TrackedProductListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TrackedProductListResponse> | TrackedProductListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/tracked-products', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListTrackedProductsApiTrackedProductsGetResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateTrackedProductApiTrackedProductsPostMockHandler = (overrideResponse?: TrackedProductResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TrackedProductResponse> | TrackedProductResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/tracked-products', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateTrackedProductApiTrackedProductsPostResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetTrackedProductApiTrackedProductsTrackedProductIdGetMockHandler = (overrideResponse?: TrackedProductResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TrackedProductResponse> | TrackedProductResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/tracked-products/:trackedProductId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTrackedProductApiTrackedProductsTrackedProductIdGetResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateTrackedProductApiTrackedProductsTrackedProductIdPatchMockHandler = (overrideResponse?: TrackedProductResponse | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<TrackedProductResponse> | TrackedProductResponse), options?: RequestHandlerOptions) => {
  return http.patch('*/api/tracked-products/:trackedProductId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateTrackedProductApiTrackedProductsTrackedProductIdPatchResponseMock(),
      { status: 200
      })
  }, options)
}

export const getArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostMockHandler = (overrideResponse?: TrackedProductResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TrackedProductResponse> | TrackedProductResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/tracked-products/:trackedProductId/archive', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostMockHandler = (overrideResponse?: TrackedProductResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TrackedProductResponse> | TrackedProductResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/tracked-products/:trackedProductId/restore', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostMockHandler = (overrideResponse?: TrackedProductResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TrackedProductResponse> | TrackedProductResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/tracked-products/:trackedProductId/refresh', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostResponseMock(),
      { status: 202
      })
  }, options)
}
export const getTrackedProductsMock = () => [
  getListTrackedProductsApiTrackedProductsGetMockHandler(),
  getCreateTrackedProductApiTrackedProductsPostMockHandler(),
  getGetTrackedProductApiTrackedProductsTrackedProductIdGetMockHandler(),
  getUpdateTrackedProductApiTrackedProductsTrackedProductIdPatchMockHandler(),
  getArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostMockHandler(),
  getRestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostMockHandler(),
  getRefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostMockHandler()]
