/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  TrackedProductCreateRequest,
  TrackedProductListResponse,
  TrackedProductResponse,
  TrackedProductUpdateRequest
} from '../index.schemas';




  export const getTrackedProducts = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary List Tracked Products
 */
const listTrackedProductsApiTrackedProductsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrackedProductListResponse>> => {
    return axiosInstance.get(
      `/api/tracked-products`,options
    );
  }
/**
 * @summary Create Tracked Product
 */
const createTrackedProductApiTrackedProductsPost = (
    trackedProductCreateRequest: TrackedProductCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrackedProductResponse>> => {
    return axiosInstance.post(
      `/api/tracked-products`,
      trackedProductCreateRequest,options
    );
  }
/**
 * @summary Get Tracked Product
 */
const getTrackedProductApiTrackedProductsTrackedProductIdGet = (
    trackedProductId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrackedProductResponse>> => {
    return axiosInstance.get(
      `/api/tracked-products/${trackedProductId}`,options
    );
  }
/**
 * @summary Update Tracked Product
 */
const updateTrackedProductApiTrackedProductsTrackedProductIdPatch = (
    trackedProductId: string,
    trackedProductUpdateRequest: TrackedProductUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrackedProductResponse>> => {
    return axiosInstance.patch(
      `/api/tracked-products/${trackedProductId}`,
      trackedProductUpdateRequest,options
    );
  }
/**
 * @summary Archive Tracked Product
 */
const archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost = (
    trackedProductId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrackedProductResponse>> => {
    return axiosInstance.post(
      `/api/tracked-products/${trackedProductId}/archive`,undefined,options
    );
  }
/**
 * @summary Restore Tracked Product
 */
const restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost = (
    trackedProductId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrackedProductResponse>> => {
    return axiosInstance.post(
      `/api/tracked-products/${trackedProductId}/restore`,undefined,options
    );
  }
/**
 * @summary Refresh Tracked Product
 */
const refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost = (
    trackedProductId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TrackedProductResponse>> => {
    return axiosInstance.post(
      `/api/tracked-products/${trackedProductId}/refresh`,undefined,options
    );
  }
return {listTrackedProductsApiTrackedProductsGet,createTrackedProductApiTrackedProductsPost,getTrackedProductApiTrackedProductsTrackedProductIdGet,updateTrackedProductApiTrackedProductsTrackedProductIdPatch,archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost,restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost,refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost}};
export type ListTrackedProductsApiTrackedProductsGetResult = AxiosResponse<TrackedProductListResponse>
export type CreateTrackedProductApiTrackedProductsPostResult = AxiosResponse<TrackedProductResponse>
export type GetTrackedProductApiTrackedProductsTrackedProductIdGetResult = AxiosResponse<TrackedProductResponse>
export type UpdateTrackedProductApiTrackedProductsTrackedProductIdPatchResult = AxiosResponse<TrackedProductResponse>
export type ArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostResult = AxiosResponse<TrackedProductResponse>
export type RestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostResult = AxiosResponse<TrackedProductResponse>
export type RefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostResult = AxiosResponse<TrackedProductResponse>
