/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  TokenResponse,
  UserPublicResponse
} from '../index.schemas';


export const getRegisterApiAuthRegisterPostResponseMock = (overrideResponse: Partial<Extract<UserPublicResponse, object>> = {}): UserPublicResponse => ({id: faker.string.uuid(), email: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getLoginApiAuthLoginPostResponseMock = (overrideResponse: Partial<Extract<TokenResponse, object>> = {}): TokenResponse => ({access_token: faker.string.alpha({length: {min: 10, max: 20}}), refresh_token: faker.string.alpha({length: {min: 10, max: 20}}), token_type: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getRefreshApiAuthRefreshPostResponseMock = (overrideResponse: Partial<Extract<TokenResponse, object>> = {}): TokenResponse => ({access_token: faker.string.alpha({length: {min: 10, max: 20}}), refresh_token: faker.string.alpha({length: {min: 10, max: 20}}), token_type: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getRegisterApiAuthRegisterPostMockHandler = (overrideResponse?: UserPublicResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserPublicResponse> | UserPublicResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/register', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRegisterApiAuthRegisterPostResponseMock(),
      { status: 201
      })
  }, options)
}

export const getLoginApiAuthLoginPostMockHandler = (overrideResponse?: TokenResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenResponse> | TokenResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginApiAuthLoginPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRefreshApiAuthRefreshPostMockHandler = (overrideResponse?: TokenResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenResponse> | TokenResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/refresh', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRefreshApiAuthRefreshPostResponseMock(),
      { status: 200
      })
  }, options)
}

export const getLogoutApiAuthLogoutPostMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/logout', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getAuthMock = () => [
  getRegisterApiAuthRegisterPostMockHandler(),
  getLoginApiAuthLoginPostMockHandler(),
  getRefreshApiAuthRefreshPostMockHandler(),
  getLogoutApiAuthLogoutPostMockHandler()]
