/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  LogoutRequest,
  RefreshRequest,
  RegisterRequest,
  TokenResponse,
  UserPublicResponse
} from '../index.schemas';




  export const getAuth = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Register
 */
const registerApiAuthRegisterPost = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserPublicResponse>> => {
    return axiosInstance.post(
      `/api/auth/register`,
      registerRequest,options
    );
  }
/**
 * @summary Login
 */
const loginApiAuthLoginPost = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TokenResponse>> => {
    return axiosInstance.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }
/**
 * @summary Refresh
 */
const refreshApiAuthRefreshPost = (
    refreshRequest: RefreshRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TokenResponse>> => {
    return axiosInstance.post(
      `/api/auth/refresh`,
      refreshRequest,options
    );
  }
/**
 * @summary Logout
 */
const logoutApiAuthLogoutPost = (
    logoutRequest: LogoutRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/auth/logout`,
      logoutRequest,options
    );
  }
return {registerApiAuthRegisterPost,loginApiAuthLoginPost,refreshApiAuthRefreshPost,logoutApiAuthLogoutPost}};
export type RegisterApiAuthRegisterPostResult = AxiosResponse<UserPublicResponse>
export type LoginApiAuthLoginPostResult = AxiosResponse<TokenResponse>
export type RefreshApiAuthRefreshPostResult = AxiosResponse<TokenResponse>
export type LogoutApiAuthLogoutPostResult = AxiosResponse<void>
