services:
  backend:
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://findog:findog@db:5432/findog

  frontend:
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8001
