/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  UserPublicResponse
} from '../index.schemas';




  export const getUsers = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Get Me
 */
const getMeApiUsersMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserPublicResponse>> => {
    return axiosInstance.get(
      `/api/users/me`,options
    );
  }
return {getMeApiUsersMeGet}};
export type GetMeApiUsersMeGetResult = AxiosResponse<UserPublicResponse>
