/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  UserPublicResponse
} from '../index.schemas';


export const getGetMeApiUsersMeGetResponseMock = (overrideResponse: Partial<Extract<UserPublicResponse, object>> = {}): UserPublicResponse => ({id: faker.string.uuid(), email: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getGetMeApiUsersMeGetMockHandler = (overrideResponse?: UserPublicResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserPublicResponse> | UserPublicResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMeApiUsersMeGetResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUsersMock = () => [
  getGetMeApiUsersMeGetMockHandler()]
