/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Register
 */
export const registerApiAuthRegisterPostBodyPasswordMin = 8;



export const RegisterApiAuthRegisterPostBody = zod.object({
  "email": zod.string().email(),
  "password": zod.string().min(registerApiAuthRegisterPostBodyPasswordMin)
})

/**
 * @summary Login
 */
export const LoginApiAuthLoginPostBody = zod.object({
  "email": zod.string().email(),
  "password": zod.string()
})

export const loginApiAuthLoginPostResponseTokenTypeDefault = `bearer`;

export const LoginApiAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(loginApiAuthLoginPostResponseTokenTypeDefault)
})

/**
 * @summary Refresh
 */
export const RefreshApiAuthRefreshPostBody = zod.object({
  "refresh_token": zod.string()
})

export const refreshApiAuthRefreshPostResponseTokenTypeDefault = `bearer`;

export const RefreshApiAuthRefreshPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(refreshApiAuthRefreshPostResponseTokenTypeDefault)
})

/**
 * @summary Logout
 */
export const LogoutApiAuthLogoutPostBody = zod.object({
  "refresh_token": zod.string()
})

