/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LogoutRequest {
  refresh_token: string;
}

export interface RefreshRequest {
  refresh_token: string;
}

export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
}

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
}

export interface TrackedProductCreateRequest {
  /** @minLength 1 */
  source_url: string;
  /** @minLength 1 */
  source_title: string;
  source_platform?: string | null;
  source_image_url?: string | null;
  source_price_amount?: number | string | null;
  source_currency?: string | null;
}

export interface TrackedProductResponse {
  id: string;
  user_id: string;
  source_url: string;
  source_platform: string | null;
  source_title: string;
  source_image_url: string | null;
  source_price_amount: string | null;
  source_currency: string | null;
  normalized_query: string | null;
  product_fingerprint: string | null;
  monitoring_status: string;
  restock_alert_enabled: boolean;
  lowest_price_tracking_enabled: boolean;
  last_checked_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface TrackedProductListResponse {
  items: TrackedProductResponse[];
}

export interface TrackedProductUpdateRequest {
  source_title?: string | null;
  restock_alert_enabled?: boolean | null;
  lowest_price_tracking_enabled?: boolean | null;
}

export interface UserPublicResponse {
  id: string;
  email: string;
  created_at: string;
}

export type HealthApiHealthGet200 = {[key: string]: string};

