/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Tracked Products
 */
export const listTrackedProductsApiTrackedProductsGetResponseItemsItemSourcePriceAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ListTrackedProductsApiTrackedProductsGetResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().uuid(),
  "user_id": zod.string().uuid(),
  "source_url": zod.string(),
  "source_platform": zod.union([zod.string(),zod.null()]),
  "source_title": zod.string(),
  "source_image_url": zod.union([zod.string(),zod.null()]),
  "source_price_amount": zod.union([zod.string().regex(listTrackedProductsApiTrackedProductsGetResponseItemsItemSourcePriceAmountOneRegExp),zod.null()]),
  "source_currency": zod.union([zod.string(),zod.null()]),
  "normalized_query": zod.union([zod.string(),zod.null()]),
  "product_fingerprint": zod.union([zod.string(),zod.null()]),
  "monitoring_status": zod.string(),
  "restock_alert_enabled": zod.boolean(),
  "lowest_price_tracking_enabled": zod.boolean(),
  "last_checked_at": zod.union([zod.string().datetime({}),zod.null()]),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
}))
})

/**
 * @summary Create Tracked Product
 */


export const createTrackedProductApiTrackedProductsPostBodySourcePriceAmountTwoRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const CreateTrackedProductApiTrackedProductsPostBody = zod.object({
  "source_url": zod.string().min(1),
  "source_title": zod.string().min(1),
  "source_platform": zod.union([zod.string(),zod.null()]).optional(),
  "source_image_url": zod.union([zod.string(),zod.null()]).optional(),
  "source_price_amount": zod.union([zod.number(),zod.string().regex(createTrackedProductApiTrackedProductsPostBodySourcePriceAmountTwoRegExp),zod.null()]).optional(),
  "source_currency": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Get Tracked Product
 */
export const GetTrackedProductApiTrackedProductsTrackedProductIdGetParams = zod.object({
  "tracked_product_id": zod.string().uuid()
})

export const getTrackedProductApiTrackedProductsTrackedProductIdGetResponseSourcePriceAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const GetTrackedProductApiTrackedProductsTrackedProductIdGetResponse = zod.object({
  "id": zod.string().uuid(),
  "user_id": zod.string().uuid(),
  "source_url": zod.string(),
  "source_platform": zod.union([zod.string(),zod.null()]),
  "source_title": zod.string(),
  "source_image_url": zod.union([zod.string(),zod.null()]),
  "source_price_amount": zod.union([zod.string().regex(getTrackedProductApiTrackedProductsTrackedProductIdGetResponseSourcePriceAmountOneRegExp),zod.null()]),
  "source_currency": zod.union([zod.string(),zod.null()]),
  "normalized_query": zod.union([zod.string(),zod.null()]),
  "product_fingerprint": zod.union([zod.string(),zod.null()]),
  "monitoring_status": zod.string(),
  "restock_alert_enabled": zod.boolean(),
  "lowest_price_tracking_enabled": zod.boolean(),
  "last_checked_at": zod.union([zod.string().datetime({}),zod.null()]),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Update Tracked Product
 */
export const UpdateTrackedProductApiTrackedProductsTrackedProductIdPatchParams = zod.object({
  "tracked_product_id": zod.string().uuid()
})




export const UpdateTrackedProductApiTrackedProductsTrackedProductIdPatchBody = zod.object({
  "source_title": zod.union([zod.string().min(1),zod.null()]).optional(),
  "restock_alert_enabled": zod.union([zod.boolean(),zod.null()]).optional(),
  "lowest_price_tracking_enabled": zod.union([zod.boolean(),zod.null()]).optional()
})

export const updateTrackedProductApiTrackedProductsTrackedProductIdPatchResponseSourcePriceAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const UpdateTrackedProductApiTrackedProductsTrackedProductIdPatchResponse = zod.object({
  "id": zod.string().uuid(),
  "user_id": zod.string().uuid(),
  "source_url": zod.string(),
  "source_platform": zod.union([zod.string(),zod.null()]),
  "source_title": zod.string(),
  "source_image_url": zod.union([zod.string(),zod.null()]),
  "source_price_amount": zod.union([zod.string().regex(updateTrackedProductApiTrackedProductsTrackedProductIdPatchResponseSourcePriceAmountOneRegExp),zod.null()]),
  "source_currency": zod.union([zod.string(),zod.null()]),
  "normalized_query": zod.union([zod.string(),zod.null()]),
  "product_fingerprint": zod.union([zod.string(),zod.null()]),
  "monitoring_status": zod.string(),
  "restock_alert_enabled": zod.boolean(),
  "lowest_price_tracking_enabled": zod.boolean(),
  "last_checked_at": zod.union([zod.string().datetime({}),zod.null()]),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Archive Tracked Product
 */
export const ArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostParams = zod.object({
  "tracked_product_id": zod.string().uuid()
})

export const archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostResponseSourcePriceAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const ArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostResponse = zod.object({
  "id": zod.string().uuid(),
  "user_id": zod.string().uuid(),
  "source_url": zod.string(),
  "source_platform": zod.union([zod.string(),zod.null()]),
  "source_title": zod.string(),
  "source_image_url": zod.union([zod.string(),zod.null()]),
  "source_price_amount": zod.union([zod.string().regex(archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostResponseSourcePriceAmountOneRegExp),zod.null()]),
  "source_currency": zod.union([zod.string(),zod.null()]),
  "normalized_query": zod.union([zod.string(),zod.null()]),
  "product_fingerprint": zod.union([zod.string(),zod.null()]),
  "monitoring_status": zod.string(),
  "restock_alert_enabled": zod.boolean(),
  "lowest_price_tracking_enabled": zod.boolean(),
  "last_checked_at": zod.union([zod.string().datetime({}),zod.null()]),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Restore Tracked Product
 */
export const RestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostParams = zod.object({
  "tracked_product_id": zod.string().uuid()
})

export const restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostResponseSourcePriceAmountOneRegExp = new RegExp('^(?!^[-+.]\*$)[+-]?0\*\\d\*\\.?\\d\*$');


export const RestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostResponse = zod.object({
  "id": zod.string().uuid(),
  "user_id": zod.string().uuid(),
  "source_url": zod.string(),
  "source_platform": zod.union([zod.string(),zod.null()]),
  "source_title": zod.string(),
  "source_image_url": zod.union([zod.string(),zod.null()]),
  "source_price_amount": zod.union([zod.string().regex(restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostResponseSourcePriceAmountOneRegExp),zod.null()]),
  "source_currency": zod.union([zod.string(),zod.null()]),
  "normalized_query": zod.union([zod.string(),zod.null()]),
  "product_fingerprint": zod.union([zod.string(),zod.null()]),
  "monitoring_status": zod.string(),
  "restock_alert_enabled": zod.boolean(),
  "lowest_price_tracking_enabled": zod.boolean(),
  "last_checked_at": zod.union([zod.string().datetime({}),zod.null()]),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Refresh Tracked Product
 */
export const RefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostParams = zod.object({
  "tracked_product_id": zod.string().uuid()
})

