/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  TrackedProductCreateRequest,
  TrackedProductListResponse,
  TrackedProductResponse,
  TrackedProductUpdateRequest
} from '../index.schemas';

import { axiosInstance } from '../../mutator/axios-instance';




/**
 * @summary List Tracked Products
 */
export const listTrackedProductsApiTrackedProductsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<TrackedProductListResponse>(
      {url: `/api/tracked-products`, method: 'GET', signal
    },
      );
    }
  



export const getListTrackedProductsApiTrackedProductsGetQueryKey = () => {
    return [
    `/api/tracked-products`
    ] as const;
    }

    
export const getListTrackedProductsApiTrackedProductsGetQueryOptions = <TData = Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTrackedProductsApiTrackedProductsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>> = ({ signal }) => listTrackedProductsApiTrackedProductsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTrackedProductsApiTrackedProductsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>>
export type ListTrackedProductsApiTrackedProductsGetQueryError = unknown


export function useListTrackedProductsApiTrackedProductsGet<TData = Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>,
          TError,
          Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTrackedProductsApiTrackedProductsGet<TData = Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>,
          TError,
          Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTrackedProductsApiTrackedProductsGet<TData = Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tracked Products
 */

export function useListTrackedProductsApiTrackedProductsGet<TData = Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTrackedProductsApiTrackedProductsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTrackedProductsApiTrackedProductsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Tracked Product
 */
export const createTrackedProductApiTrackedProductsPost = (
    trackedProductCreateRequest: TrackedProductCreateRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<TrackedProductResponse>(
      {url: `/api/tracked-products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: trackedProductCreateRequest, signal
    },
      );
    }
  


export const getCreateTrackedProductApiTrackedProductsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrackedProductApiTrackedProductsPost>>, TError,{data: TrackedProductCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTrackedProductApiTrackedProductsPost>>, TError,{data: TrackedProductCreateRequest}, TContext> => {

const mutationKey = ['createTrackedProductApiTrackedProductsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTrackedProductApiTrackedProductsPost>>, {data: TrackedProductCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTrackedProductApiTrackedProductsPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTrackedProductApiTrackedProductsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTrackedProductApiTrackedProductsPost>>>
    export type CreateTrackedProductApiTrackedProductsPostMutationBody = TrackedProductCreateRequest
    export type CreateTrackedProductApiTrackedProductsPostMutationError = HTTPValidationError

    /**
 * @summary Create Tracked Product
 */
export const useCreateTrackedProductApiTrackedProductsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrackedProductApiTrackedProductsPost>>, TError,{data: TrackedProductCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTrackedProductApiTrackedProductsPost>>,
        TError,
        {data: TrackedProductCreateRequest},
        TContext
      > => {
      return useMutation(getCreateTrackedProductApiTrackedProductsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Tracked Product
 */
export const getTrackedProductApiTrackedProductsTrackedProductIdGet = (
    trackedProductId: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<TrackedProductResponse>(
      {url: `/api/tracked-products/${trackedProductId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTrackedProductApiTrackedProductsTrackedProductIdGetQueryKey = (trackedProductId: string,) => {
    return [
    `/api/tracked-products/${trackedProductId}`
    ] as const;
    }

    
export const getGetTrackedProductApiTrackedProductsTrackedProductIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError = HTTPValidationError>(trackedProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrackedProductApiTrackedProductsTrackedProductIdGetQueryKey(trackedProductId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>> = ({ signal }) => getTrackedProductApiTrackedProductsTrackedProductIdGet(trackedProductId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(trackedProductId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrackedProductApiTrackedProductsTrackedProductIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>>
export type GetTrackedProductApiTrackedProductsTrackedProductIdGetQueryError = HTTPValidationError


export function useGetTrackedProductApiTrackedProductsTrackedProductIdGet<TData = Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError = HTTPValidationError>(
 trackedProductId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrackedProductApiTrackedProductsTrackedProductIdGet<TData = Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError = HTTPValidationError>(
 trackedProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrackedProductApiTrackedProductsTrackedProductIdGet<TData = Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError = HTTPValidationError>(
 trackedProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Tracked Product
 */

export function useGetTrackedProductApiTrackedProductsTrackedProductIdGet<TData = Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError = HTTPValidationError>(
 trackedProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrackedProductApiTrackedProductsTrackedProductIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrackedProductApiTrackedProductsTrackedProductIdGetQueryOptions(trackedProductId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Tracked Product
 */
export const updateTrackedProductApiTrackedProductsTrackedProductIdPatch = (
    trackedProductId: string,
    trackedProductUpdateRequest: TrackedProductUpdateRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<TrackedProductResponse>(
      {url: `/api/tracked-products/${trackedProductId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: trackedProductUpdateRequest, signal
    },
      );
    }
  


export const getUpdateTrackedProductApiTrackedProductsTrackedProductIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrackedProductApiTrackedProductsTrackedProductIdPatch>>, TError,{trackedProductId: string;data: TrackedProductUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTrackedProductApiTrackedProductsTrackedProductIdPatch>>, TError,{trackedProductId: string;data: TrackedProductUpdateRequest}, TContext> => {

const mutationKey = ['updateTrackedProductApiTrackedProductsTrackedProductIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTrackedProductApiTrackedProductsTrackedProductIdPatch>>, {trackedProductId: string;data: TrackedProductUpdateRequest}> = (props) => {
          const {trackedProductId,data} = props ?? {};

          return  updateTrackedProductApiTrackedProductsTrackedProductIdPatch(trackedProductId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTrackedProductApiTrackedProductsTrackedProductIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTrackedProductApiTrackedProductsTrackedProductIdPatch>>>
    export type UpdateTrackedProductApiTrackedProductsTrackedProductIdPatchMutationBody = TrackedProductUpdateRequest
    export type UpdateTrackedProductApiTrackedProductsTrackedProductIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Tracked Product
 */
export const useUpdateTrackedProductApiTrackedProductsTrackedProductIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrackedProductApiTrackedProductsTrackedProductIdPatch>>, TError,{trackedProductId: string;data: TrackedProductUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTrackedProductApiTrackedProductsTrackedProductIdPatch>>,
        TError,
        {trackedProductId: string;data: TrackedProductUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateTrackedProductApiTrackedProductsTrackedProductIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Archive Tracked Product
 */
export const archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost = (
    trackedProductId: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<TrackedProductResponse>(
      {url: `/api/tracked-products/${trackedProductId}/archive`, method: 'POST', signal
    },
      );
    }
  


export const getArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost>>, TError,{trackedProductId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost>>, TError,{trackedProductId: string}, TContext> => {

const mutationKey = ['archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost>>, {trackedProductId: string}> = (props) => {
          const {trackedProductId} = props ?? {};

          return  archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost(trackedProductId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostMutationResult = NonNullable<Awaited<ReturnType<typeof archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost>>>
    
    export type ArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostMutationError = HTTPValidationError

    /**
 * @summary Archive Tracked Product
 */
export const useArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost>>, TError,{trackedProductId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveTrackedProductApiTrackedProductsTrackedProductIdArchivePost>>,
        TError,
        {trackedProductId: string},
        TContext
      > => {
      return useMutation(getArchiveTrackedProductApiTrackedProductsTrackedProductIdArchivePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Restore Tracked Product
 */
export const restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost = (
    trackedProductId: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<TrackedProductResponse>(
      {url: `/api/tracked-products/${trackedProductId}/restore`, method: 'POST', signal
    },
      );
    }
  


export const getRestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost>>, TError,{trackedProductId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost>>, TError,{trackedProductId: string}, TContext> => {

const mutationKey = ['restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost>>, {trackedProductId: string}> = (props) => {
          const {trackedProductId} = props ?? {};

          return  restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost(trackedProductId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostMutationResult = NonNullable<Awaited<ReturnType<typeof restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost>>>
    
    export type RestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostMutationError = HTTPValidationError

    /**
 * @summary Restore Tracked Product
 */
export const useRestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost>>, TError,{trackedProductId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreTrackedProductApiTrackedProductsTrackedProductIdRestorePost>>,
        TError,
        {trackedProductId: string},
        TContext
      > => {
      return useMutation(getRestoreTrackedProductApiTrackedProductsTrackedProductIdRestorePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Refresh Tracked Product
 */
export const refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost = (
    trackedProductId: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<TrackedProductResponse>(
      {url: `/api/tracked-products/${trackedProductId}/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getRefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost>>, TError,{trackedProductId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost>>, TError,{trackedProductId: string}, TContext> => {

const mutationKey = ['refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost>>, {trackedProductId: string}> = (props) => {
          const {trackedProductId} = props ?? {};

          return  refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost(trackedProductId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostMutationResult = NonNullable<Awaited<ReturnType<typeof refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost>>>
    
    export type RefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostMutationError = HTTPValidationError

    /**
 * @summary Refresh Tracked Product
 */
export const useRefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost>>, TError,{trackedProductId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPost>>,
        TError,
        {trackedProductId: string},
        TContext
      > => {
      return useMutation(getRefreshTrackedProductApiTrackedProductsTrackedProductIdRefreshPostMutationOptions(options), queryClient);
    }
    