/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UserPublicResponse
} from '../index.schemas';

import { axiosInstance } from '../../mutator/axios-instance';




/**
 * @summary Get Me
 */
export const getMeApiUsersMeGet = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<UserPublicResponse>(
      {url: `/api/users/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeApiUsersMeGetQueryKey = () => {
    return [
    `/api/users/me`
    ] as const;
    }

    
export const getGetMeApiUsersMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiUsersMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeApiUsersMeGet>>> = ({ signal }) => getMeApiUsersMeGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiUsersMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeApiUsersMeGet>>>
export type GetMeApiUsersMeGetQueryError = unknown


export function useGetMeApiUsersMeGet<TData = Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiUsersMeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiUsersMeGet<TData = Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiUsersMeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiUsersMeGet<TData = Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiUsersMeGet<TData = Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiUsersMeGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeApiUsersMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




