/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FinDog API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health
 */
export const HealthApiHealthGetResponse = zod.record(zod.string(), zod.string())

